### ISSUE TITLE
Error in running inference_single.py

### ISSUE THREAD

**Issue by kdinashi** [Graylab/DFMDock#3]
When trying to run inference_single.py on two pdb files, I get the following error:

line 515, in inference
    model = DFMDock.load_from_checkpoint(
............
raise ConfigKeyError(f"Missing key {key!s}")
omegaconf.errors.ConfigAttributeError: Missing key crop_size
    full_key: crop_size
    object_type=dict

Could you help me resolve this error?

**Comment by lchu11** [comment]
Just edited. Let me know if it works. Thanks!

**Comment by kdinashi** [comment]
Thank you for the update. Now the error has changed:

Traceback (most recent call last):
  File "/home/kimia/DFMDock/src/inference_single.py", line 12, in <module>
    inference(args.pdb_1, args.pdb_2)
  File "/home/kimia/DFMDock/src/inference_base.py", line 645, in inference
    rec_pos, lig_pos, rot_update, tr_update, outputs = Euler_Maruyama_sampler(
  File "/home/kimia/DFMDock/src/inference_base.py", line 426, in Euler_Maruyama_sampler
    output = model(batch) 
  File "/home/kimia/miniconda3/envs/DFMDock/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/kimia/miniconda3/envs/DFMDock/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/kimia/DFMDock/src/models/score_model_mlsb.py", line 62, in forward
    outputs = self.net(batch, predict=True)
  File "/home/kimia/miniconda3/envs/DFMDock/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/kimia/miniconda3/envs/DFMDock/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/kimia/DFMDock/src/models/score_net_mlsb.py", line 370, in forward
    edge = self.spatial_embed(spatial_matrix) + self.positional_embed(position_matrix)
  File "/home/kimia/miniconda3/envs/DFMDock/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/kimia/miniconda3/envs/DFMDock/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/kimia/miniconda3/envs/DFMDock/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 117, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (204304x66 and 67x128)

I appreciate your assistance!

**Comment by aggelos-michael-papadopoulos** [comment]
Hello i am facing the same error!

**Comment by lchu11** [comment]
sorry for the bug, should work now

**Comment by aggelos-michael-papadopoulos** [comment]
still the same error {I have done everything from the beginning}

python src/inference_single.py /home/angepapa/PycharmProjects/DeepSurf2.0/test_data/pdbs/DBv5/DBv5_bound/1B6C_receptor_1.pdb /home/angepapa/PycharmProjects/DeepSurf2.0/test_data/pdbs/DBv5/DBv5_bound/1B6C_antigen_1_1.pdb

  File "/home/angepapa/anaconda3/envs/DFMDock/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 117, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (187489x66 and 67x128)

**Comment by lchu11** [comment]
Sorry I forgot to update the repo, could you please try again?

**Comment by aggelos-michael-papadopoulos** [comment]
The same error again. Does it work on your setup?

**Comment by lchu11** [comment]
turns out it imported the incorrect weights. Should be working now, sorry for the trouble.

**Comment by aggelos-michael-papadopoulos** [comment]
Yep, it works now, thanks!!

Just a minor suggestion;

I think the inference line:
`python src/inference_single.py path_to_input_pdb_1 path_to_input_pdb_2`

should change to:
`python src/inference_single.py  path_to_receptor_input_pdb path_to_ligand_input_pdb`
